spring:
  datasource:
    url: jdbc:h2:~/test
    password: sa
    username: sa
    driver-class-name: org.h2.Driver  jpa:    hibernate:      ddl-auto: create
    show-sql: true
    
server:  port: 9000
  